global:
  edition: ce
  ingress:
    configureCertmanager: false
  hosts:
    domain: gitlab.svc
    https: true
    gitlab:
      https: true
    registry:
      servicePort: 5000
      https: true
    minio:
      https: false
nginx-ingress:
  enabled: false
certmanager:
  install: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  unicorn:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
registry:
  enabled: false
  hpa:
    minReplicas: 1
    maxReplicas: 1
