#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ param.NAMESPACE }}-database-pv
  labels:
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  storageClassName: epoch-ita-database-volume-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/epoch/ita/{{ param.NAMESPACE }}-pv/database
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ param.NODE }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epoch-ita-database-volume
  namespace: {{ param.NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: epoch-ita-database-volume-storage
  volumeMode: Filesystem
  volumeName: {{ param.NAMESPACE }}-database-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ param.NAMESPACE }}-file-pv
  labels:
    type: local
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  storageClassName: epoch-ita-file-volume-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/epoch/ita/{{ param.NAMESPACE }}-pv/file
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ param.NODE }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epoch-ita-file-volume
  namespace: {{ param.NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: epoch-ita-file-volume-storage
  volumeMode: Filesystem
  volumeName: {{ param.NAMESPACE }}-file-pv
