#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-ita-conf
  namespace: epoch-workspace
data:
  ita_table_update.sql: |
    UPDATE A_ACCOUNT_LIST SET PW_LAST_UPDATE_TIME = '2999-12-31 23:59:58' WHERE USER_ID = 1;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-automation
spec:
  selector:
    matchLabels:
      app: it-automation
  replicas: 1
  template:
    metadata:
      labels:
        app: it-automation
    spec:
      volumes:
      - name: epoch-ita-conf
        configMap:
          name: epoch-ita-conf
      containers:
      - name: it-automation
        image: exastro/it-automation:1.6.3-ja
        ports:
        - containerPort: 80
        - containerPort: 443
        securityContext:
          privileged: true
        volumeMounts:
        - name: epoch-ita-conf
          mountPath: /app/epoch/tmp
---
apiVersion: v1
kind: Service
metadata:
  name: it-automation
spec:
  type: LoadBalancer
  selector:
    app: it-automation
  ports:
    - name: "8084"
      port: 8084
      targetPort: 80
      nodePort: 30905
    - name: "10483"
      port: 10483
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ita-worker
spec:
  selector:
    matchLabels:
      name: ita-worker
  replicas: 1
  template:
    metadata:
      labels:
        name: ita-worker
    spec:
      containers:
      - name: ita-worker
        image: exastro/epoch-ita-worker:0.1.0_20210624_1421
        ports:
        - containerPort: 22
        command: ["sh", "-c"]
        args:
        - |
          echo "export HTTPS_PROXY=$HTTPS_PROXY"  >  /etc/profile.d/99-proxy.sh;
          echo "export https_proxy=$https_proxy"  >> /etc/profile.d/99-proxy.sh;
          echo "export HTTP_PROXY=$HTTP_PROXY"    >> /etc/profile.d/99-proxy.sh;
          echo "export http_proxy=$http_proxy"    >> /etc/profile.d/99-proxy.sh;
          echo "export HTTPS_PROXY=$HTTPS_PROXY"  >  /etc/environment;
          echo "export https_proxy=$https_proxy"  >> /etc/environment;
          echo "export HTTP_PROXY=$HTTP_PROXY"    >> /etc/environment;
          echo "export http_proxy=$http_proxy"    >> /etc/environment;
          /usr/sbin/sshd -De

---
apiVersion: v1
kind: Service
metadata:
  name: ita-worker
  labels:
    name: ita-worker
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    name: ita-worker
