#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: epoch-monitoring-api-config
  namespace: epoch-system
data:
  EPOCH_CONTROL_ARGOCD_PROTOCOL: "http"
  EPOCH_CONTROL_ARGOCD_HOST: "epoch-control-argocd-api"
  EPOCH_CONTROL_ARGOCD_PORT: "8000"
  EPOCH_CONTROL_ITA_PROTOCOL: "http"
  EPOCH_CONTROL_ITA_HOST: "epoch-control-ita-api"
  EPOCH_CONTROL_ITA_PORT: "8000"
  EPOCH_RS_CD_RESULT_PROTOCOL: "http"
  EPOCH_RS_CD_RESULT_HOST: "epoch-rs-cd-result-api"
  EPOCH_RS_CD_RESULT_PORT: "8000"
  EPOCH_RS_LOGS_PROTOCOL: "http"
  EPOCH_RS_LOGS_HOST: "epoch-rs-logs-api"
  EPOCH_RS_LOGS_PORT: "8000"
  PYTHONIOENCODING: utf-8
  EPOCH_MONITORING_ARGOCD_INTERVAL_SEC: "5"
  EPOCH_MONITORING_ITA_INTERVAL_SEC: "5"
  EPOCH_MONITORING_ARGOCD_ERROR_RETRY_COUNT: "5"
  EPOCH_MONITORING_ITA_ERROR_RETRY_COUNT: "5"
