#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: exastro-platform-authentication-infra
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31180
  - name: https
    port: 8443
    targetPort: 8443
    nodePort: 31182
  selector:
    app: keycloak
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: exastro-platform-authentication-infra
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:15.0.2
        env:
        - name: DB_VENDOR
          valueFrom:
            configMapKeyRef:
              name: exastro-platform-authentication-infra-env
              key: KEYCLOAK_DB_VENDOR
        - name: DB_ADDR
          valueFrom:
            configMapKeyRef:
              name: exastro-platform-authentication-infra-env
              key: KEYCLOAK_DB_HOST
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: exastro-platform-authentication-infra-env
              key: KEYCLOAK_DB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: exastro-platform-authentication-infra-secret
              key: KEYCLOAK_DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exastro-platform-authentication-infra-secret
              key: KEYCLOAK_DB_PASSWORD
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: exastro-platform-authentication-infra-secret
              key: KEYCLOAK_USER
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exastro-platform-authentication-infra-secret
              key: KEYCLOAK_PASSWORD
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
