#   Copyright 2019 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-and-push
  namespace: epoch-tekton-pipelines
spec:
  workspaces:
    - name: git-source
      description: The git repo
  # パラメータセクション  実行時に Kind: PipelineRun から変数を与える。
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: master
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToDockerfile
      description: The path to the build Dockerfile
      default: Dockerfile
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
    - name: git_ref
  tasks:
    # ステップ #0
    # 初期処理
    - name: task-start
      taskRef:
        name: pipeline-task-start
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: git_ref
          value: "$(params.git_ref)"
    # ステップ #1
    # GitHubからソースコードをワークスペースにクローン（取得）する
    - name: task-git-clone
      taskRef:
        name: pipeline-task-git-clone
      runAfter:
        - task-start
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
        - name: sslVerify
          value: "false"

    # ステップ #2 
    # コンテナのビルドとレジストリへ登録  Kanikoタスクにパラメータを渡してビルド実行、イメージをレジストリへ登録
    - name: task-kaniko-build
      taskRef:
        name: pipeline-task-kaniko
      runAfter:
        - task-git-clone
      workspaces:
        - name: source
          workspace: git-source
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: DOCKERFILE
          value: $(params.pathToDockerfile)
        - name: IMAGE
          value: $(params.imageUrl):$(tasks.task-start.results.container_registry_image_tag)
